### ISSUE TITLE
Project does not compile with jboss-remoting 3.2.2.GA

### ISSUE THREAD

**Issue by goldmann** [jbossas/jboss-remote-naming#2]
The latest remoting is used by AS 7.1.0.Final but jboss-remote-naming is not compiling with it:

<pre>
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project jboss-remote-naming: Compilation failure
[ERROR] bootstrap class path not set in conjunction with -source 1.6
[ERROR] /home/goldmann/work/jboss-remote-naming/BUILD/jboss-remote-naming-1.0.1.Final/src/main/java/org/jboss/naming/remote/client/cache/ConnectionCache.java:[81,12] error: ConnectionCache.ConnectionWrapper is not abstract and does not override abstract method getUserInfo() in Connection
</pre>
